// Generated by CoffeeScript 1.10.0
(function() {
  var slice = [].slice;

  module.exports = {
    extend: exports.extend = function(object, properties) {
      var key, val;
      for (key in properties) {
        val = properties[key];
        object[key] = val;
      }
      return object;
    },
    merge: function() {
      var base, extension, extensions, i, len, object;
      base = arguments[0], extensions = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      object = extend(base, {});
      for (i = 0, len = extensions.length; i < len; i++) {
        extension = extensions[i];
        object = module.exports.extend(object, extension);
      }
      return object;
    },
    copy: function(base) {
      return module.exports.extend(base, {});
    },
    trim: function(string, characters) {
      var index, pattern;
      characters = (characters + '').replace(/[.?*+^$[\]\\(){}|-]/g, '\\$&');
      string = string.replace(/^\s\s*/, '');
      pattern = new RegExp("[" + characters + "]");
      index = string.length;
      while (pattern.test(str.charAt(--index))) {
        continue;
      }
      return string.slice(0, index + 1);
    }
  };

}).call(this);
